### ISSUE TITLE
Do you think adding selection of download folder? 

### ISSUE THREAD

**Issue by toprak** [whew/manyame#3]
I mean, imagine you have an anime folder on /user/whew/ and you want to download it here, also you could add function that can create a folder name of the files like [HorribleSubs] One Piece.

**Comment by whew** [comment]
Good idea, thanks!

**Comment by whew** [comment]
>selection of download folder

Done, https://github.com/whew/manyame/commit/e8ff8046c6311f39f9f6a34ff686a7c4e3c97cbf

>add function that can create a folder name of the files like [HorribleSubs] One Piece

Will do it today or tomorrow.

**Comment by whew** [comment]
>add function that can create a folder name of the files like [HorribleSubs] One Piece

https://github.com/whew/manyame/commit/59e61260f0755261062504ef7dc008b9ade3cef8 done. I will release it in an hour.

**Comment by whew** [comment]
https://github.com/whew/manyame/releases/tag/1.2.3 released for windows

**Comment by toprak** [comment]
I am looking forward for linux one

**Comment by whew** [comment]
@toprak https://github.com/whew/manyame#linux

Depending on the distro, you need to install jq and fzf. After that, compile xdccget and put the binary file in $PATH. After that you can use manyame.sh

For example (for Ubuntu):

```
sudo apt-get install fzf
sudo apt-get install jq
git clone https://github.com/Fantastic-Dave/xdccget 
cd xdccget
sudo apt-get install libssl-dev build-essential
make
cp xdccget ~/.local/bin/
cd ..
git clone https://github.com/whew/manyame
cd manyame
bash manyame.sh
```

**Comment by whew** [comment]
One way or another, I consider the main question solved. Now you can choose the folder where the files will be downloaded. Also each title will be downloaded to its own folder. Among other things, implemented a simple concept of a configuration file in which you can store some project-related variables.

**Comment by toprak** [comment]
@whew I guess you got it wrong ```[HorribleSubs] One Piece.``` Imagine, you are downloading grand blue as a batch, I did not main manyame should create folder each episode, just one and download episodes there. Thanks for your hardwork.
