### ISSUE TITLE
About names of folders that manyame create

### ISSUE THREAD

**Issue by toprak** [whew/manyame#5]
I guess you got it wrong this section [HorribleSubs] One Piece at #3 . Imagine, you are downloading grand blue as a batch from irc and it contains [HorribleSubs] in the first part of the sentence, I did not main manyame should create folder each episode, just create one folder named [HorribleSubs] Grand Blue and download episodes there. Thanks for your hardwork.

**Comment by whew** [comment]
I think (moreover, I am sure) that it is not necessary. Suppose you download different subbers. Then put one title in different folders? Now it creates just a folder named as title of series. I will record the video to show.

**Comment by toprak** [comment]
>>Now it creates just a folder named as title of series
That's GREAT!

**Comment by toprak** [comment]
I do not know why but sometimes it writes 62; while searching files

**Comment by whew** [comment]
Please post screenshot.

**Comment by toprak** [comment]
![Screenshot_2020-09-19_13-51-03](https://user-images.githubusercontent.com/43301560/93665441-31b5a580-fa7f-11ea-9afa-5d80f405d485.png)
as you can guess I wrote wtf and you see the result

**Comment by whew** [comment]
I think it's the issue with your distro's `fzf`. On Arch, Win and Ubuntu I didn't found any issues. Try to reinstall `fzf`.
