### ISSUE TITLE
Windows : Selecting multiple files (batch download)

### ISSUE THREAD

**Issue by parandar** [whew/manyame#6]
Hi, 

Just installed the last release on my windows pc, I can fetch multiple episodes without any issue (no episode number + the search index top of the cmd) but I wasn't able to figure out how to select multiple files.

All keystrokes are going as text into the search top of the terminal, and only enter seems to have an effect, aka downloading only the file I'm hovering.

I'm pretty noob in a terminal so there must be a key or something I don't know to select them, and you should be able to help me with that.

Thank you in advance, and great job with your tool !

**Comment by whew** [comment]
Press 'tab' near that files you want to check. After all, press Enter.

**Comment by parandar** [comment]
Thank you very much, I would've swear I tried that ^^
Well, time to finally watch the last season of nanatsu no taizai !
